config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stores
  root 'stores#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # This initializer is creating your memory-only guest users

    if user
      if user.has_role? :admin
        can :manage, :all
      end
      if user.has_role? :store_keeper
        can :update, Store
      end
      if user.has_role? :user
        can :vote, Store
      end
    else
      can :read, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role
  include Mongoid::Document
  has_and_belongs_to_many :users
  belongs_to :resource, :polymorphic => true

  field :name, :type => String

  index({
    :name => 1,
    :resource_type => 1,
    :resource_id => 1
  },
  { :unique => true})

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/store.rb
class Store
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :open, type: Mongoid::Boolean
  field :image, type: String
  field :photos, type: Array
  field :tags, type: Array
  field :description, type: String
  field :lat, type: BigDecimal
  field :lng, type: BigDecimal
  field :votes, type: Integer, default: 0
  field :props, type: Hash

  def self.voteUp(id)
    s = Store.find(id)
    s.votes++
    s.save
  end

  def tags_list=(arg)
    self.tags = arg.split(',').map { |v| v.strip }
  end

  def tags_list
    self.tags.join(', ') if self.tags
  end

  def photos_list=(arg)
    if arg
      self.photos = arg.split(',').map { |v| v.strip }
    end
  end

  def photos_list
    self.photos.join(', ') if self.photos
  end

  def props_hash=(arg)
    if arg.size > 2
      self.props = JSON.parse arg.gsub('=>', ':')
    end
  end

  def props_hash
    self.props.to_s
  end

  def as_indexed_json(options={})
    as_json()
  end

  def main_image
     photos[0] if photos
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #check_authorization

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show, :home]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
    authorize! :read, @stores
  end

  def home
    @stores = Store.all
  end

  def vote
    authorize! :vote, @store
    Store.voteUp(params[:id])
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)
    authorize! :manage, @store
    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:photos_list, :tags_list, :props_hash, :name, :email, :open, :image, :photos, :tags, :description, :lat, :lng, :votes, :props)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tttruck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>



</head>
<body>


      <div class="navbar navbar-default navbar-static-top">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">RailsMongoidDevise</a>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <% if current_user %>
                  <li>Hello <%= current_user.email %></li>
              <% else %>
                  <li> <%= link_to('Register', {:action=>"new", :controller=>"devise/registrations"})  %> </li>
              <% end %>

            <% if user_signed_in? %>
              <li>

              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
            <% else %>
              <li>
              <%= link_to('Login', new_user_session_path)  %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-lg-9">
            <%= bootstrap_flash %>
            <%= yield %>
        </div><!--/row-->

      </div> <!-- /container -->

</body>
</html>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :open %><br>
    <%= f.check_box :open %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :photos_list %><br>
    <%= f.text_field :photos_list %>
  </div>
  <div class="field">
    <%= f.label :tags_list %><br>
    <%= f.text_field :tags_list %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :votes %><br>
    <%= f.text_field :votes %>
  </div>
  <div class="field">
    <%= f.label :props_hash %><br>
    <%= f.text_field :props_hash %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/home.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
   <div class="col-sm-4">
     <% @stores.take(5).each do |store| %>
      <div class="row">
        <h3><%= store.name %></h3>
        <img src="<%= store.main_image %>"/>
        <span>Votes: <%= store.votes %></span>
      </div>
     <% end %>
   </div>
   <div class="col-sm-8">
     <div id="map"  style="width:600px;height:600px"></div>
     <script>
       var map;
       function initMap() {
         map = new google.maps.Map(document.getElementById('map'), {
           center: {lat: -22.9155366, lng: -43.223151},
           zoom: 13
         });
         var markers = []; 
         <% @stores.take(5).each do |store| %>
            markers.push(
              new google.maps.Marker({
                position: {lat: <%= store.lat %>, lng: <%= store.lng %>},
                map: map,
                title: "<%= store.name %>"
              })
            );
         <% end %>
       }
     </script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtxN3UsF1vAhU_2z3x1pGU0nTcnem1qoU&callback=initMap"
     async defer></script>
   </div>
</div>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stores</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Open</th>
      <th>Image</th>
      <th>Photos</th>
      <th>Tags</th>
      <th>Description</th>
      <th>Lat</th>
      <th>lng</th>
      <th>Props</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.email %></td>
        <td><%= store.open %></td>
        <td><%= store.image %></td>
        <td><img src="<%= store.photos  ? store.photos[0] : ''  %>"/></td>
        <td><%= store.tags %></td>
        <td><%= store.description %></td>
        <td><%= store.lat %></td>
        <td><%= store.lng %></td>
        <td><%= store.props %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @store.email %>
</p>

<p>
  <strong>Open:</strong>
  <%= @store.open %>
</p>

<p>
  <strong>Image:</strong>
  <%= @store.image %>
</p>

<p>
  <strong>Photos:</strong>
  <%= @store.photos %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @store.tags %>
</p>

<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @store.lat %>
</p>

<p>
  <strong>lng:</strong>
  <%= @store.lng %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @store.votes %>
</p>

<p>
  <strong>Props:</strong>
  <%= @store.props %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>